name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the action on version tag pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential curl

      - name: Build project
        run: make all

      - name: Create tarball
        run: make dist

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-distribution
          path: dist/build/linux.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download distribution artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-distribution

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release version ${{ github.ref_name }} is available.
          draft: false
          prerelease: false

      - name: Upload tarball to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/build/linux.tar.gz
          asset_name: linux.tar.gz
          asset_content_type: application/gzip

